; SPDX-License-Identifier: GPL-3.0-or-later
; Supported MUI customization; retain Tauri's installation and upgrade logic.
SetFont "Microsoft YaHei UI" 9
!define MUI_BGCOLOR "242424"
!define MUI_TEXTCOLOR "EDEDED"
!define MUI_INSTFILESPAGE_COLORS "EDEDED 303030"
!define IRIS_INSTALLER_UI "${__FILEDIR__}\ui.nsh"
!define MUI_PAGE_CUSTOMFUNCTION_SHOW IrisWelcomeShow
!define MUI_WELCOMEPAGE_TITLE "$(IrisWelcomeTitle)"
!define MUI_WELCOMEPAGE_TEXT "$(IrisWelcomeText)"
!define MUI_FINISHPAGE_TITLE "$(IrisFinishTitle)"
!define MUI_FINISHPAGE_TEXT "$(IrisFinishText)"
!define MUI_FINISHPAGE_RUN_NOTCHECKED
!define MUI_DIRECTORYPAGE_TEXT_TOP "$(IrisRequirements)$\r$\n$(IrisScope)"

LangString IrisEyebrow 2052 "伊人  /  IRIS                         WINDOWS · CPU BETA"
LangString IrisEyebrow 1033 "IRIS                                      WINDOWS · CPU BETA"
LangString IrisHero 2052 "让每一次选片，更专注。"
LangString IrisHero 1033 "A clearer view of your photos."
LangString IrisIntro 2052 "本地照片工作台，从浏览到决定。"
LangString IrisIntro 1033 "A local workspace, from browsing to decisions."
LangString IrisBrowse 2052 "看清每一个细节"
LangString IrisBrowse 1033 "See the details"
LangString IrisBrowseBody 2052 "浏览照片、放大查看，集中比较。"
LangString IrisBrowseBody 1033 "Browse, zoom and compare your photos."
LangString IrisChoose 2052 "留下值得保留的"
LangString IrisChoose 1033 "Keep what matters"
LangString IrisChooseBody 2052 "用标记整理选择，让选片有条理。"
LangString IrisChooseBody 1033 "Use marks to organize your selections."
LangString IrisAnalyze 2052 "按需开启本地分析"
LangString IrisAnalyze 1033 "Analyze when you need it"
LangString IrisAnalyzeBody 2052 "默认模型随包提供，不必另行下载。"
LangString IrisAnalyzeBody 1033 "Default models are included in this package."
LangString IrisSteps 2052 "准备   —   安装位置   —   安装   —   完成"
LangString IrisSteps 1033 "PREPARE   —   LOCATION   —   INSTALL   —   READY"
LangString IrisScope 2052 "仅为当前用户安装 · 安装程序不会移动或修改照片"
LangString IrisScope 1033 "For this account only · Setup does not modify your photos"
LangString IrisRequirements 2052 "运行需要 WebView2 与 VC++ 2015–2022 x64。"
LangString IrisRequirements 1033 "Requires WebView2 and VC++ 2015–2022 x64."
LangString IrisPreviewTitle 2052 "你的下一张好照片"
LangString IrisPreviewTitle 1033 "YOUR NEXT SELECT"
LangString IrisPreviewNote 2052 "浏览  /  比较  /  标记"
LangString IrisPreviewNote 1033 "BROWSE / COMPARE / MARK"

LangString IrisWelcomeTitle 2052 "安装 伊人 / Iris"
LangString IrisWelcomeTitle 1033 "Install Iris"
LangString IrisWelcomeText 2052 "为本地照片，留一处专注的工作空间。$\r$\n$\r$\n浏览、比较与标记照片，按需使用本地分析。$\r$\n$\r$\n应用将安装到当前 Windows 用户的文件夹。默认分析模型随安装包提供。$\r$\n$\r$\n需要 WebView2 和 Visual C++ 2015–2022 x64 运行库。$\r$\n$\r$\n选择“下一步”继续。"
LangString IrisWelcomeText 1033 "A focused workspace for your local photos.$\r$\n$\r$\nBrowse, compare and mark photos, with local analysis when you need it.$\r$\n$\r$\nInstalls for your Windows account. Default analysis models are included.$\r$\n$\r$\nRequires WebView2 and Visual C++ 2015–2022 x64 runtimes.$\r$\n$\r$\nChoose Next to continue."
LangString IrisFinishTitle 2052 "伊人已安装"
LangString IrisFinishTitle 1033 "Iris is installed"
LangString IrisFinishText 2052 "一切就绪，可以开始选片了。$\r$\n$\r$\n打开伊人，选择照片文件夹后开始扫描。扫描完成后，可按需启动分析。$\r$\n$\r$\n安装程序没有移动或修改你的照片。$\r$\n$\r$\n选择“完成”关闭安装程序。"
LangString IrisFinishText 1033 "Your workspace is ready.$\r$\n$\r$\nOpen Iris and choose a photo folder to scan. Start analysis when you need it.$\r$\n$\r$\nThe installer has not moved or modified your photos.$\r$\n$\r$\nChoose Finish to close setup."
